# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14bf5c39bc39294aafaf8170d4cce2e957377c5ab8fd603edf706df839513b019eb23b7025ae83b5cc1b43b081060504f4bf1fd6d595fc822936ff1524bcabb8
  google_oauth_client_id: 604193143251-iid5gtan84r9cndag6ldgk4qtrkrvvng.apps.googleusercontent.com
  google_oauth_client_secret: 83CUIeZmf1MYTKsA2wD524bP

test:
  secret_key_base: 06fde821063bc44dcecee32c401e0deec190bd3f2e0b514fe72137f4c29e9fee6df8ac3585593064dab7eb51267a521f7fc9e8170eb693d15bf940a958743be8
  google_oauth_client_id: 604193143251-iid5gtan84r9cndag6ldgk4qtrkrvvng.apps.googleusercontent.com
  google_oauth_client_secret: 83CUIeZmf1MYTKsA2wD524bP

# Production credentials are encrypted. Use `bin/rails secrets:edit` to make changes
